[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  'council/=lib/council/contracts',
  'openzeppelin/=lib/openzeppelin-contracts/contracts',
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
